# Generated by Django 3.2.8 on 2021-11-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sample_input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sample_output',
            field=models.TextField(blank=True),
        ),
    ]
