# Generated by Django 3.2.8 on 2021-11-18 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211119_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sample_input',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sample_output',
        ),
    ]
