# Generated by Django 3.2.8 on 2021-11-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211119_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
